### ISSUE TITLE
Installation of the patch for novice AZERTY users

### ISSUE THREAD

**Issue by ShiroKrow** [Log-s/flipperzero-contributions#1]
Hello ! I'm surrounded by AZERTY keyboard and this is a very needed patch, a VERY unique one at that.

For starters, I'm not familiar with dockers and all, I can't find the firmware folder where 'furi_hal_usb_hid.h" is suppose to be and /fbt is unknowm to me. 

Could you explain the patching process in more depth ?

Many thanks in advance !

**Comment by Log-s** [comment]
Hi !

I'm going to try to explain, but I'm not sure I can't be more precise than what the README says ;)

Once you cloned the official repo from here: replace the file in
```
flipperzero-firmware
 └── firmware
     └── targets
         └── furi_hal_include
```

Then you have to compile the firmware with preferred methods, also described on the official firmware repo linked above. The docker command I gave in my README is just one example (the easiest according to me, because you just have to copy-paste it)

`sudo docker-compose up -d && sudo docker-compose exec dev ./fbt`

To answer your question, about dockers, if you are using Linux, you can install the necessary software via you packet manager (example with apt: `sudo apt install docker docker-compose`) and then run the command above. `fbt` is a utility executable that comes with the flipperzero firmware, it's located in its root folder.

**HOWEVER**

The patch doesn't seem to be working on recent versions of the firmware. I'll have to take a look at it and update my patch. In the meantime, you can use the `ALTSTRING` instruction in your scripts, instead of the `STRING` instruction. It's supposed to type in AZERTY.
